### ISSUE TITLE
fails sends with project defined address

### ISSUE THREAD

**Issue by fengyedou** [chrodriguez/redmine_per_project_sender#1]
I have enable the custom field 'project-sender-email'and set one email address in one project, Then I tested like below:

adding a news in this project, but the mail is still sent by redmine global address.

I am not sure if my understanding is right.

**Comment by chrodriguez** [comment]
which version of redmine are you using?

**Comment by fengyedou** [comment]
2.3.2 :)

**Comment by Wayn0** [comment]
--Hi, I am having the same issue with 3.2.1 but I will look into the code and see what I can do--
This actually works with 3.2.1, I had another plugin that was conflicting with this one.

**Comment by ImageGroupUK** [comment]
Hi, 

This doesnt seem to work with Redmine 3.2.2. Am I missing something? Or perhaps it is conflicting with another plugin?
![image](https://cloud.githubusercontent.com/assets/12294212/15854960/9b799bdc-2ca4-11e6-9752-484e9c66f1a9.png)

**Comment by ImageGroupUK** [comment]
It seems this conflicts with Event Notifications plugin. When this was disabled then redmine crashes on saving the issue with "Undefined Method 'ascii_only?'"

**Comment by chrodriguez** [comment]
I've updated the plugin fixing this issue, please try it again updating to the latest commit. I've tested it with redmine 3.3-stable
